[package]
name = "better-ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = {version = '0.23.2'}
tabled = {version = '0.7.0', features = ["color"]}
comfy-table = {version = '6.0.0'}